version: '3'
services:
  selenium-app:
    build: .
    container_name: selenium-python
    volumes:
      - .:/app
    environment:
      - DISPLAY=:99
    networks:
      - selenium-network
    depends_on:
      - selenium-hub

  selenium-hub:
    image: selenium/standalone-chrome:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge
